name: l32_seer
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.8.16
  - pip:
    - attrs==22.2.0
    - click==8.1.3
    - cloudpickle==1.6.0
    - configargparse==1.5.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - fastjsonschema==2.16.3
    - flask==2.2.3
    - fonttools==4.38.0
    - future==0.18.3
    - gym==0.17.3
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipywidgets==8.0.4
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - nbformat==5.5.0
    - numba==0.56.4
    - numpy==1.23.0
    - numpy-quaternion==2020.11.2.17.0.49
    - open3d==0.16.0
    - packaging==23.0
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.13.1
    - pybullet==3.0.9
    - pyglet==1.5.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pywin32==305
    - pyzmq==25.0.0
    - scipy==1.10.1
    - setuptools==50.3.2
    - tenacity==8.2.1
    - torch==1.13.1
    - tornado==6.2
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - zipp==3.14.0
    - pydantic==1.10.*
    - pytest==7.2.*
