on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: l32_seer
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          pip install --editable pybullet_multigoal_gym
          pip install --editable pybullet_multigoal_implementation
          pip install --editable .
      - run: |
          python3 -m pytest
